### ISSUE TITLE
Hang during shutdown

### ISSUE THREAD

**Issue by sambonfire** [sammyfreg/netImgui#59] opened 2024-07-23 00:23 UTC
**Describe the bug**
We're occasionally experiencing a hang when shutting down netimgui.

This happens randomly; it isn't 100% consistent.  Seeing this on windows using winsock.

**To Reproduce**
1. Start NetImgui client
2. No need to even connect to a server
3. Shut down
4. Randomly, process will hang in NetImgui_Api.cpp in the Shutdown() method, while spinning in this loop:
```
	while( gpClientInfo->IsActive() )
		std::this_thread::yield();
```

**Expected behavior**
The program does not hang while shutting down

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**

I haven't looked at the code enough to say this with certainty, but it looks like there might be a race condition in the shutdown code where it is cleaning up the socket.

In `Shutdown()`, `Disconnect()` is called, which in turn sets `client.mbDisconnectRequest` to true and also calls `client.KillSocketListen()`:

https://github.com/sammyfreg/netImgui/blob/master/Code/Client/Private/NetImgui_Api.cpp#L102

KillSocketListen() does an atomic exchange of the socket pointer and then calls Disconnect() which cleans up the socket and it's resources.

However, if the thread context switches to the `CommunicationsHost` thread just before those things happen:

https://github.com/sammyfreg/netImgui/blob/5b76352825ad1f62991161fcf70a02aedf33880c/Code/Client/Private/NetImgui_Client.cpp#L405

The check for a null listen socket can be skipped because it's still valid, and then it can call to `ListenConnect`.

If the context then switches back to the thread shutting down, the socket is disconnected and cleaned up, but this means that the `CommunicationsHost` thread is now using an invalid socket.

When we attach a debugger to our hung process, we see that the `CommunicationsHost` thread is just sitting in the winsock `accept(...)` call which never returns.

This is probably rare because the `mbDisconnectRequest` slightly guards against this possibility.

I'm not sure what the best thing to do would be here, but it seems like one option would be to protect some of this code with a critical section, or alternatively don't call `KillSocketListen()` in the `Disconnect` call and instead let the thread clean that up itself.  Or perhaps Disconnect() should just set the flag `mbDisconnectRequest = true` and then sleep and poll the `mbListenThreadActive` variable until the `CommunicationsHost` thread has had a chance to shutdown and clean up the connection.

I haven't looked extensively at the code so these might be bad suggestions, just throwing out ideas.

**Comment by sammyfreg** [comment] 2024-07-23 00:41
Thank you for the detailed description.

I have not seen this myself, but it is most likely a multi-threading contention issue as suggested. I tried to use as few critical sections as possible to avoid impacting the performance of people's codebase, and rely on atomic where I think I can get away with it. Seems like this unlikely case might be happening. I'll look at it later. As suggested, a critical section should fix this, if you want to patch it locally in the meantime.

**Comment by sammyfreg** [comment] 2024-08-03 14:34
I'm currently looking into this. The original reason we have the main thread try to kill the SocketListen, is that the waiting for a connection is configured to be a blocking operation, and the only way to stop it was to kill the socket on another thread. Thinking about it, I guess I could also try to connect to it too, causing a connection failure and the loop to resume. Might be safer than a critical section that wouldn't be able to release itself either, because ListenConnect is blocking. Will see what can be done and try to reproduce the problem with well placed thread::yields.

**Comment by sammyfreg** [comment] 2024-08-03 15:06
@sambonfire Could you let me know if this changelist fix your problem? Wasn't able to get it myself, but I removed the socket access race condition by implementing my above comment, so should be good now. 

Thanks for the investigation you did into this, it was really helpfull.

**Comment by sambonfire** [comment] 2024-08-13 20:46
Will give it a shot thanks 👍

**Comment by sammyfreg** [comment] 2024-12-08 23:11
Code handling communication was entirely reworked and previous fix should also have taken care fo the problem. 
Closing this.

**Closed by sammyfreg** 2024-12-08 23:11 UTC
